language: python
python:
  - "2.7" 
  - "3.5"

branches:
  only:
    - master
    - develop

before_install:
  - sudo apt-get update
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - sudo apt-get -y update && sudo apt-get install -y -qq fsl-core
  - source /etc/fsl/fsl.sh
  - export FSLOUTPUTTYPE=NIFTI_GZ
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  # - conda update -q conda # seems to break travis
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels conda-forge
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip scipy numpy pandas scikit-learn
  - pip install nibabel nilearn pytest pytest-cov coveralls pytest-pep8 future

install:
  # Replace dep1 dep2 ... with your dependencies
  - echo $PWD/skbold/data/test_data/mock_subjects/sub00* | xargs -n 1 cp -rs $PWD/skbold/data/test_data/run1.feat
  - python setup.py install

script:
  - ./run_pytest.sh

after_success:
    - coveralls
